# Generated by Django 5.1.7 on 2025-03-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_classroom_group_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="dominant_trait",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
