# Generated by Django 5.1.7 on 2025-03-11 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_student_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='mainapp.classroom')),
                ('students', models.ManyToManyField(related_name='groups', to='mainapp.student')),
            ],
        ),
    ]
