# Generated by Django 5.1.7 on 2025-03-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Group_student',
        ),
    ]
